  CONSTRUCT {
      ?mandataris a mandaat:Mandataris;
                  org:holds ?mandaat;
                  mandaat:isBestuurlijkeAliasVan ?persoon;
                  mu:uuid ?uuid;
                  mandaat:start ?start;
                  mandaat:einde ?einde;
                  mandaat:status ?status.
  }
  WHERE {
    GRAPH $tmpGraph {
    ?artikel a ?type.
    ?artikel ?mandaatRelatie ?mandataris.
    ?mandataris a mandaat:Mandataris.
    OPTIONAL {?mandataris org:holds ?mandaat.}
    OPTIONAL {?mandataris mandaat:isBestuurlijkeAliasVan ?persoon.}
    OPTIONAL {?mandataris mandaat:start ?start.}
    OPTIONAL {?mandataris mu:uuid ?uuid.}
    OPTIONAL {?mandataris mandaat:einde ?einde.}
    OPTIONAL {?mandataris mandaat:status ?status.}
    OPTIONAL  {?mandataris mandaat:rangorde ?rangorde}
    VALUES ?mandaatRelatie { mandaat:bekrachtigtAanstellingVan ext:bekrachtigtAanstellingVan}
    VALUES ?type { besluit:Artikel besluit:Besluit }
    }
    ?mandaat ?p ?o.
  }
