CONSTRUCT {
    ?fractie a mandaat:Fractie.
    ?lidmaatschap a org:Membership.
    ?periode a <http://purl.org/dc/terms/PeriodOfTime>.

    ?mandataris <http://www.w3.org/ns/org#hasMembership> ?lidmaatschap.
    ?lidmaatschap <http://www.w3.org/ns/org#memberDuring> ?periode.
    ?periode <http://data.vlaanderen.be/ns/generiek#begin> ?begin.
    ?lidmaatschap <http://www.w3.org/ns/org#organisation> ?fractie.
    ?fractie <http://mu.semte.ch/vocabularies/ext/isFractietype> ?type.
    ?fractie <http://www.w3.org/ns/org#memberOf> ?bestuursorgaan.
    ?fractie <http://www.w3.org/ns/org#linkedTo> ?eenheid.
    ?fractie <https://www.w3.org/ns/regorg#legalName> ?naam.

    ?fractie ext:generatedFrom ext:mandatenExtractorService.
    ?lidmaatschap ext:generatedFrom ext:mandatenExtractorService.
    ?periode ext:generatedFrom ext:mandatenExtractorService.
}
WHERE {
  GRAPH $tmpGraph {
      ?fractie a mandaat:Fractie.
      ?lidmaatschap a org:Membership.
      OPTIONAL { ?periode a <http://purl.org/dc/terms/PeriodOfTime>. }

      ?mandataris <http://www.w3.org/ns/org#hasMembership> ?lidmaatschap.
      OPTIONAL { ?lidmaatschap <http://www.w3.org/ns/org#memberDuring> ?periode.}
      ?lidmaatschap <http://www.w3.org/ns/org#organisation> ?fractie.

      OPTIONAL { ?periode <http://data.vlaanderen.be/ns/generiek#begin> ?begin. }
      OPTIONAL { ?fractie <http://mu.semte.ch/vocabularies/ext/isFractietype> ?type. }
      ?fractie <http://www.w3.org/ns/org#memberOf> ?bestuursorgaan.
      ?fractie <http://www.w3.org/ns/org#linkedTo> ?eenheid.
      OPTIONAL { ?fractie <http://www.w3.org/ns/regorg#legalName> ?naam. }
  }
}
