CONSTRUCT {
?fractie a mandaat:Fractie;
         ?p ?o.
?lidmaatschap a org:Membership;
              ?lp ?lo.
?mandataris org:hasMembership ?lidmaatschap.
?tijdsinterval ?tp ?to.

}
WHERE {
GRAPH $tmpGraph {
  ?fractie a mandaat:Fractie;
           ?p ?o.
  OPTIONAL {
    ?lidmaatschap org:organisation ?fractie;
                  ?lp ?lo.
    ?mandataris org:hasMembership ?lidmaatschap.
  }
  OPTIONAL {
   ?lidmaatschap org:organisation ?fractie;
                 org:memberDuring ?tijdsinterval.
   ?tijdsinterval ?tp ?to.
   }
}
}
